### ISSUE TITLE
Adjust chronological timeline order based on Disney+ information

### ISSUE THREAD

**Issue by Coteh** [Coteh/mcu-rewatch#128]
Based on "Marvel Cinematic Universe in Timeline Order" section seen here:
https://www.disneyplus.com/brand/marvel
- Thor: The Dark World should be before Iron Man 3
- Black Panther should be before Doctor Strange

**Comment by JadeDickinson** [comment]
I'm working on this one if that's ok?

I noticed running locally that this necessitates redownloading the images - will this affect the deployed version of the app?

**Comment by Coteh** [comment]
Go for it! :)

Before server starts, a separate build step downloads posters from IMDB and puts them in a directory. This happens when production is deployed as well so you shouldn’t have to worry about it.

On Oct 17, 2020, at 5:11 PM, Jade Dickinson <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm working on this one if that's ok?

I noticed running locally that this necessitates redownloading the images - will this affect the deployed version of the app?
